DroitPluriel-appli/justicie

- components/Accueil/Accueil.test.tsx
- components/Accueil/Accueil.tsx
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
> S75 fix link open new tab

- .eslintrc
- components/Header/useHeader.ts
- components/RechercherParHandicap/RechercherParHandicap.module.css
- components/RechercherParHandicap/RechercherParHandicap.tsx
- components/RechercherUnLieu/RechercherUnLieu.module.css
- components/RechercherUnLieu/RechercherUnLieu.test.tsx
- components/RechercherUnLieu/RechercherUnLieu.tsx
- components/RechercherUnLieu/useRechercherUnLieu.ts
- components/Stepper/Stepper.module.css
- components/Stepper/Stepper.tsx
- configuration/Paths.ts
- configuration/frontDependencies.ts
- configuration/globals.css
- configuration/testHelper.tsx
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
- package.json
- pages/rechercher-par-handicap.tsx
- pages/rechercher-un-lieu.tsx
- stryker.conf.json
- yarn.lock
> S80 Geolocalisation

- components/Header/Header.module.css
- components/NosCriteresDAccessibilite/NosCriteresDAccessibilite.module.css
- configuration/globals.css
> Fix secondary color & title "Nos critères d'accessibilite"

- components/RechercherParHandicap/RechercherParHandicap.tsx
- components/RechercherUnLieu/RechercherUnLieu.test.tsx
- components/RechercherUnLieu/RechercherUnLieu.tsx
- components/RechercherUnLieu/useRechercherUnLieu.ts
- configuration/globals.css
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
> S80 Griser le bouton quand on bloque la géolocalisation

- .stylelintrc
- components/Accueil/Accueil.test.tsx
- components/Accueil/Accueil.tsx
- components/FoireAuxQuestions.tsx
- components/Footer/Footer.module.css
- components/Footer/Footer.test.tsx
- components/Footer/Footer.tsx
- components/RechercherParHandicap/RechercherParHandicap.module.css
- components/RechercherUneConsultationJuridique/RechercherUneConsultationJuridique.module.css
- components/RechercherUneConsultationJuridique/RechercherUneConsultationJuridique.test.tsx
- components/RechercherUneConsultationJuridique/RechercherUneConsultationJuridique.tsx
- components/RechercherUneConsultationJuridique/useRechercherUneConsultationJuridique.ts
- components/RenseignerUneAdresse/RenseignerUneAdresse.module.css
- configuration/Paths.ts
- configuration/globals.css
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
- pages/faq.tsx
- pages/foire-aux-questions.tsx
- pages/rechercher-un-lieu.tsx
- pages/rechercher-une-consultation-juridique.tsx
> S82 rechercher par handicap

- backend/backDependencies.ts
- components/Lieu/Lieu.tsx
- pages/lieu/[...id].tsx
- pages/resultats-liste.tsx
- pages/resultats-plan.tsx
> S89 Création de la page Lieu

- components/CarteLieu/CarteLieu.module.css
- components/CarteLieu/CarteLieu.tsx
- components/CarteLieu/useCarteLieu.ts
- components/RechercherParHandicap/useRechercherParHandicap.ts
- components/Resultats/ResultatsListe.test.tsx
- components/Resultats/ResultatsListe.tsx
- components/Resultats/ResultatsPlan.test.tsx
- components/Resultats/ResultatsPlan.tsx
- configuration/useQueryUtilities.ts
> S85 Corrections

- configuration/wording/WordingFr.tsx
> Corrections wording sprint2

- pages/_app.tsx
> Add `/` in links in _app.tsx

- components/BoutonModeSombre/BoutonModeSombre.test.tsx
- components/BoutonModeSombre/BoutonModeSombre.tsx
- components/BoutonModeSombre/useBoutonModeSombre.ts
- components/Header/Header.test.tsx
- components/Header/Header.tsx
- configuration/useTheme.ts
- configuration/wording/WordingFr.tsx
> Fix modesombre menuburger

- components/NosCriteresDAccessibilite/NosCriteresDAccessibilite.test.tsx
- components/RechercherParHandicap/RechercherParHandicap.test.tsx
- components/RechercherUneAideJuridique/RechercherUneAideJuridique.test.tsx
- components/RechercherUneAideJuridique/RechercherUneAideJuridique.tsx
- components/RechercherUneAideJuridique/useRechercherUneAideJuridique.ts
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
> S115 Message pour indiquer que le GPS est désactivé

- .github/pull_request_template.md
- components/BoutonModeSombre/useBoutonModeSombre.ts
- components/RechercherUneAideJuridique/RechercherUneAideJuridique.module.css
- components/RechercherUneAideJuridique/useRechercherUneAideJuridique.ts
- components/RenseignerUneAdresse/RenseignerUneAdresse.test.tsx
- components/RenseignerUneAdresse/RenseignerUneAdresse.tsx
- components/RenseignerUneAdresse/useRenseignerUneAdresse.ts
- configuration/wording/WordingFr.tsx
> S118 Message quand l'API Adresse ne répond plus

- components/Resultats/EnTete.module.css
- components/Resultats/EnTete.tsx
- components/Resultats/ResultatsListe.test.tsx
- components/Resultats/ResultatsPlan.test.tsx
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
> S119-S120 correction de wording

- .stylelintrc
- components/CarteLieu/CarteLieu.module.css
- components/Lieu/Lieu.module.css
- components/Pagination/Pagination.module.css
- components/RechercherParHandicap/RechercherParHandicap.module.css
- components/RechercherUneAideJuridique/RechercherUneAideJuridique.module.css
- components/RenseignerUneAdresse/RenseignerUneAdresse.module.css
- components/Resultats/EnTete.module.css
- components/Resultats/Plan.module.css
> S116 Suppression des marges modernes

- components/RechercherUneAideJuridique/RechercherUneAideJuridique.test.tsx
- components/RechercherUneAideJuridique/useRechercherUneAideJuridique.ts
> S115 GPS désactivé pour Safari

- components/CarteLieu/CarteLieu.module.css
- components/Lieu/Lieu.test.tsx
- components/Lieu/Lieu.tsx
- components/Resultats/ResultatsListe.test.tsx
- components/Resultats/ResultatsListe.tsx
- components/Resultats/ResultatsPlan.test.tsx
- components/Resultats/ResultatsPlan.tsx
- components/VotreAvis/VotreAvis.module.css
- components/VotreAvis/VotreAvis.tsx
- configuration/globals.css
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
> S96 Afficher un lien pour donner son avis

- components/RechercherParHandicap/CritereDAccessibilite.tsx
- components/RechercherParHandicap/RechercherParHandicap.test.tsx
- components/Resultats/EnTete.module.css
- components/Resultats/EnTete.tsx
- components/Resultats/ResultatsListe.test.tsx
- components/Resultats/ResultatsPlan.test.tsx
- configuration/globals.css
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
> S110 refacto page besoin accessibilite

- backend/backDependencies.ts
- backend/entities/Criteres.ts
- backend/entities/Lieu.ts
- backend/entities/LieuBuilder.ts
- backend/entities/LieuLoader.ts
- backend/infrastructure/gateways/PostgreSQLLieuLoader.test.ts
- backend/infrastructure/gateways/PostgreSQLLieuLoader.ts
- components/Accessibilites/Accessibilites.tsx
- components/Lieu/Lieu.test.tsx
- components/Resultats/ResultatsListe.test.tsx
- components/Resultats/ResultatsPlan.test.tsx
- components/Resultats/usePlan.tsx
- configuration/criteres.ts
- pages/resultats-liste.tsx
- pages/resultats-plan.tsx
> Refacto de l'entité Lieu

- backend/entities/Critere.ts
- backend/entities/Criteres.ts
- backend/entities/Lieu.ts
- backend/entities/LieuBuilder.ts
- backend/entities/LieuLoader.ts
- backend/infrastructure/gateways/PostgreSQLLieuLoader.test.ts
- backend/infrastructure/gateways/PostgreSQLLieuLoader.ts
- components/Header/Header.test.tsx
- components/Header/Header.tsx
- components/Header/useHeader.ts
- components/Lieu/Lieu.module.css
- components/RechercherUneAideJuridique/RechercherUneAideJuridique.test.tsx
- components/RechercherUneAideJuridique/RechercherUneAideJuridique.tsx
- components/RechercherUneAideJuridique/useRechercherUneAideJuridique.ts
- components/RenseignerUneAdresse/RenseignerUneAdresse.test.tsx
- components/RenseignerUneAdresse/RenseignerUneAdresse.tsx
- components/RenseignerUneAdresse/useRenseignerUneAdresse.ts
- components/Resultats/Plan.tsx
- configuration/criteres.ts
- configuration/frontDependencies.ts
- database/dotEnvConfig.ts
- pages/_app.tsx
> Suppression des onkeydown

- README.md
- components/Resultats/EnTete.tsx
- components/Resultats/ResultatsListe.test.tsx
- components/Resultats/ResultatsPlan.test.tsx
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
> S119 S120 fix wording sur les résultats de recherche

- backend/infrastructure/controllers/importerDesLieuxCron.ts
- backend/infrastructure/gateways/importerDesLieux.test.ts
- backend/infrastructure/gateways/importerDesLieux.ts
- components/RechercherParHandicap/RechercherParHandicap.test.tsx
- components/RechercherParHandicap/RechercherParHandicap.tsx
- components/Resultats/ResultatsListe.test.tsx
- components/Resultats/ResultatsListe.tsx
- components/Resultats/ResultatsPlan.test.tsx
- components/Resultats/ResultatsPlan.tsx
- configuration/useQueryUtilities.ts
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
- package.json
- pages/rechercher-par-handicap.tsx
- pages/resultats-liste.tsx
- pages/resultats-plan.tsx
- vitest.config.ts
- yarn.lock
> Utilisation de la 404 dans les pages pour vérifier si on a bien les bons paramètres GET

- backend/entities/Lieu.ts
- backend/infrastructure/gateways/PostgreSQLLieuLoader.test.ts
- backend/infrastructure/gateways/PostgreSQLLieuLoader.ts
> Distance en kilomètre plus précise

- components/Pagination/usePagination.ts
- components/RechercherParHandicap/RechercherParHandicap.tsx
- components/Resultats/ResultatsListe.test.tsx
> B130 - La pagination gère les besoins d'accessibilité

- components/Pagination/usePagination.ts
- components/Resultats/ResultatsListe.test.tsx
- components/Resultats/useEnTete.ts
> B132 - correction du lien des besoins d'accessibilités quand on est sur la page X

- components/Itineraire/Itineraire.tsx
- components/Pagination/usePagination.ts
- components/Resultats/useEnTete.ts
- components/Telephone/Telephone.tsx
> replaceAll par replace

- backend/entities/LieuBuilder.ts
- components/Footer/Footer.module.css
- components/Footer/Footer.tsx
- components/PageLieu/PageLieu.test.tsx
- components/PageLieu/PageLieu.tsx
- components/common/Preformate/Preformate.tsx
- configuration/globals.css
- configuration/wording/Wording.tsx
- configuration/wording/WordingFr.tsx
- public/initTarteAuCitron.js
- yarn.lock
> S128 - Correction fiche lieu

- components/Footer/Footer.test.tsx
- components/PageLieu/PageLieu.test.tsx
- components/PageRechercherParHandicap/PageRechercherParHandicap.test.tsx
- components/PageResultats/PageResultatsListe.test.tsx
- components/PageResultats/PageResultatsListe.tsx
- components/PageResultats/PageResultatsPlan.test.tsx
- components/PageResultats/PageResultatsPlan.tsx
- components/PageResultats/Plan/leaflet.tsx
- jest.config.ts
- pages/resultats-liste.tsx
- pages/resultats-plan.tsx
- vitest.config.ts
> refacto useRouter

- components/Footer/Footer.test.tsx
- package.json
- stryker-backend.conf.json
- stryker-frontend.conf.json
- yarn.lock
> Mise à jour de stryker

- components/PageRechercherParHandicap/PageRechercherParHandicap.tsx
- components/PageResultats/EnTete/EnTete.tsx
- components/PageResultats/PageResultatsListe.test.tsx
- components/common/Pagination/DernierePage.tsx
- components/common/Pagination/Page.tsx
- components/common/Pagination/PremierePage.tsx
- components/common/Pagination/pagination.ts
- components/common/query.ts
> utilisation des Link dynamique

- components/Footer/Footer.test.tsx
- components/Header/BoutonModeSombre/BoutonModeSombre.test.tsx
- components/Header/Header.test.tsx
- components/PageAccueil/PageAccueil.test.tsx
- components/PageFoireAuxQuestions/PageFoireAuxQuestions.test.tsx
- components/PageNosCriteresDAccessibilite/PageNosCriteresDAccessibilite.test.tsx
- components/PageRechercherUneAideJuridique/PageRechercherUneAideJuridique.test.tsx
- components/PageRenseignerUneAdresse/PageRenseignerUneAdresse.test.tsx
- components/PageResultats/PageResultatsListe.test.tsx
- components/PageResultats/PageResultatsPlan.test.tsx
> abstraction dans les tests
